### ISSUE TITLE
Figure out why SignIn/SignUp background image is creating a scrollbar

### ISSUE THREAD

**Issue by GalenChang** [club-finder-manoa/club-finder-manoa#18]
Sign Up and Sign In pages have a entry in style.css to push a background image down to the top of the footer.  Something about the image is causing a scroll bar.

Changing calc(100vh - 160px) to calc(100vh - 172px) will fix the issue in a full screen browser with a 14 inch screen.  But when browser size is reduced, whitespace appears between the footer and image.

Consider adding image to body section of css.  This will cause the image to show on every page, but we might want this to happen anyway.

**Comment by robertgodfrey** [comment]
Can mark this issue as top priority? Maybe a special flag or star or something - requires everyone's attention and focus.

**Comment by GalenChang** [comment]
This is impossible.  Changed background from bottom image to top image.
