### ISSUE TITLE
update users page 

### ISSUE THREAD

**Issue by graquepo** [club-finder-manoa/club-finder-manoa#27]
- [ ] Be able to edit/add image, name, interests, major
- [ ] Add saved clubs

**Comment by GalenChang** [comment]
We should make saved clubs a separate issue.

- Edit profile page now pulls data from the database and populates the page. 
- Made several improvements on the page itself (implemented more fields, dropdowns, etc..)
- Profile page is almost working.  Need to figure out how to pull only the logged in user's info (currently pulls all users).  This might be best as a separate issue.
- Made changes to user database schema.
- Users can almost edit their profile.  Currently running into a database access issue when user submits changes.
